#!/bin/bash
# This script was generated by classpath.py.
# It can be executed to do a "jar -xvf" for each jar in the
# CLASSPATH, so as to produce a list of all dependent classes for analysis.
# Chris Joakim, Microsoft, 2017/08/07


echo "JAR-FILE: /Users/cjoakim/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/resteasy/resteasy-jaxrs/3.0.18.Final/resteasy-jaxrs-3.0.18.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/resteasy/resteasy-jaxrs/3.0.18.Final/resteasy-jaxrs-3.0.18.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final/jboss-jaxrs-api_2.0_spec-1.0.0.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final/jboss-jaxrs-api_2.0_spec-1.0.0.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/logging/jboss-logging/3.1.4.GA/jboss-logging-3.1.4.GA.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/logging/jboss-logging/3.1.4.GA/jboss-logging-3.1.4.GA.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/resteasy/resteasy-client/3.0.18.Final/resteasy-client-3.0.18.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/resteasy/resteasy-client/3.0.18.Final/resteasy-client-3.0.18.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/resteasy/async-http-servlet-3.0/3.0.18.Final/async-http-servlet-3.0-3.0.18.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/resteasy/async-http-servlet-3.0/3.0.18.Final/async-http-servlet-3.0-3.0.18.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/resteasy/resteasy-servlet-initializer/3.0.18.Final/resteasy-servlet-initializer-3.0.18.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/resteasy/resteasy-servlet-initializer/3.0.18.Final/resteasy-servlet-initializer-3.0.18.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt/0.9.3/azure-svc-mgmt-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt/0.9.3/azure-svc-mgmt-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-core/0.9.3/azure-core-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-core/0.9.3/azure-core-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-compute/0.9.3/azure-svc-mgmt-compute-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-compute/0.9.3/azure-svc-mgmt-compute-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-network/0.9.3/azure-svc-mgmt-network-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-network/0.9.3/azure-svc-mgmt-network-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-sql/0.9.3/azure-svc-mgmt-sql-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-sql/0.9.3/azure-svc-mgmt-sql-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-storage/0.9.3/azure-svc-mgmt-storage-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-storage/0.9.3/azure-svc-mgmt-storage-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-websites/0.9.3/azure-svc-mgmt-websites-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-websites/0.9.3/azure-svc-mgmt-websites-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-media/0.9.3/azure-svc-mgmt-media-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-svc-mgmt-media/0.9.3/azure-svc-mgmt-media-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/0.9.3/azure-servicebus-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/0.9.3/azure-servicebus-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/jersey/jersey-json/1.13/jersey-json-1.13.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/jersey/jersey-json/1.13/jersey-json-1.13.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-serviceruntime/0.9.3/azure-serviceruntime-0.9.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-serviceruntime/0.9.3/azure-serviceruntime-0.9.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/4.2.0/azure-storage-4.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/4.2.0/azure-storage-4.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/1.7.1/azure-documentdb-1.7.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/1.7.1/azure-documentdb-1.7.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/json/json/20140107/json-20140107.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/json/json/20140107/json-20140107.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.1.2/adal4j-1.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.1.2/adal4j-1.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs/0.7.5/azure-eventhubs-0.7.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs/0.7.5/azure-eventhubs-0.7.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.13.0/proton-j-0.13.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.13.0/proton-j-0.13.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs-eph/0.7.2/azure-eventhubs-eph-0.7.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs-eph/0.7.2/azure-eventhubs-eph-0.7.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/redis/clients/jedis/2.8.1/jedis-2.8.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/redis/clients/jedis/2.8.1/jedis-2.8.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/4.5/oauth2-oidc-sdk-4.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/4.5/oauth2-oidc-sdk-4.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/json-smart/1.1.1/json-smart-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/json-smart/1.1.1/json-smart-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.4/lang-tag-1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.4/lang-tag-1.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/3.1.2/nimbus-jose-jwt-3.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/3.1.2/nimbus-jose-jwt-3.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/jersey/jersey-client/1.19.1/jersey-client-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/jersey/jersey-client/1.19.1/jersey-client-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4/httpcore-4.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4/httpcore-4.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar >> doc/jar_contents.txt

